[package]
name = "csgrs"
version = "0.17.0"
edition = "2024"
description = "Constructive solid geometry on meshes using BSP trees in Rust"
authors = ["Timothy Schmidt <timschmidt@gmail.com>",]
license = "MIT"
repository = "https://github.com/timschmidt/csgrs"
readme = "readme.md"
keywords = ["geometry", "physics", "csg", "slicing", "offsetting"]
categories = ["game-development", "graphics", "mathematics", "simulation", "wasm"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false
overflow-checks = false

[profile.embedded]
inherits = "release"
opt-level = "z"
lto = true

[dependencies]
anyhow = { version = "1.0.97" }
# core2 = { version = "0.4.0", default_features = false, features = ["alloc"] } # no-std, still throws errors
core2 = { version = "0.4.0", features = ["alloc"] }
nalgebra = "0.33"
geo = { version = "0.29.3", default-features = false, features = ["earcutr"] }
#geo-booleanop = "0.3.2"
geo-buf = { version = "0.1.0", optional = true } # straight-skeleton offsetting iOverlay can handle this in v2
chull = { version = "0.2.4", optional = true }
dxf = { version = "0.6.0", optional = true }
rapier3d-f64 = { version = "0.23.0", optional = true }
rapier3d = { version = "0.23.0", optional = true }
parry3d-f64  = { version = "0.18.0", optional = true }
parry3d  = { version = "0.18.0", optional = true }
rayon = { version = "1.7", optional = true }
stl_io = { version = "0.8.3", optional = true }
svg = { version = "0.18.0", optional = true }
image = { version = "0.25.5", optional = true }
contour_tracing = { version = "1.0.12", features = ["array"], optional = true }
ttf-utils = { version = "0.1.3", optional = true }
ttf-parser = { version = "0.11.0", optional = true }
hershey = { version = "0.1.1", optional = true }
fast-surface-nets = { version = "0.2.1", optional = true }
hashbrown = { version = "0.15.2", optional = true }
getrandom = { version = "0.2.15", features = ["js"], optional = true }
wasm-bindgen = { version = "0.2", optional = true }
nom = { version = "7.1.3", optional = true }

[features]
default = ["f64", "stl-io","svg-io", "dxf-io", "truetype-text", "hershey-text", "chull-io", "image-io", "metaballs", "hashmap", "sdf", "offset", "delaunay"]
parallel = [
    "rayon",
    "geo/multithreading",
    "hashbrown/rayon",
    "parry3d/parallel",
    "parry3d-f64/parallel",
    "rapier3d/parallel",
    "rapier3d-f64/parallel"
]
f64 = [
  "rapier3d-f64",
  "parry3d-f64",
]
f32 = [
  "rapier3d",
  "parry3d",
]
chull-io = [ # convex hull and minkowski sum
  "chull",
]
stl-io = [
  "stl_io",
]
svg-io = [
  "svg",
  "nom", # Parsing of things not covered by the `svg` crate
]
dxf-io = [
  "dxf",
]
truetype-text = [
  "ttf-parser",
  "ttf-utils",
]
hershey-text = [
  "hershey",
]
image-io = [
  "image",
  "contour_tracing",
]
metaballs = [
  "fast-surface-nets",
]
hashmap = [ # slice and related helper functions, is_manifold()
  "hashbrown",
]
sdf = [
  "fast-surface-nets",
]
offset = [
  "geo-buf",
]
wasm = [
  "getrandom",
  "wasm-bindgen",
]
delaunay = []
earcut = []
