#[derive(Debug, Default, Copy, Clone)]
pub struct StoreStats {
    pub requested_budget: usize,
    pub actual_budget: usize,
    pub node_size: usize,
    pub nodes_capacity: usize,
    pub total_allocations: usize,
    pub total_deallocations: usize,
    pub allocated_nodes: usize,
    pub recycled_nodes: usize,
    pub alive_nodes: usize,
    pub patterns: usize,
    pub cache_hits: usize,
    pub cache_misses: usize,
    pub leaf_nodes: usize,
    pub branch_nodes: usize,
    pub max_alive_nodes: usize,
    pub max_node_id: usize,
    pub max_ref_count: usize,
    pub max_generation: usize,
    pub generations_overflows: usize,
}
