//! Gerber (RS-274X) input and output for 2D [`Sketch`] geometry.
//!
//! The implementation uses `gerber-types` for code generation and `gerber_parser`
//! for parsing. Gerber regions map directly to filled `Sketch` polygons. Simple
//! circular, rectangular, obround, and regular-polygon flashes are imported as
//! filled shapes. Linear and circular aperture-stroked traces are imported for
//! standard apertures by constructing the swept aperture area.

use crate::csg::CSG;
use crate::float_types::{PI, Real, TAU, tolerance};
use crate::sketch::Sketch;
use geo::{Coord, Geometry, GeometryCollection, LineString, Polygon as GeoPolygon};
use gerber_types::{
    Aperture, ApertureDefinition, AxisSelect, Circle, Command, CommentContent,
    CoordinateFormat, CoordinateMode, CoordinateNumber, CoordinateOffset, Coordinates, DCode,
    ExtendedCode, FunctionCode, GCode, GerberCode, ImageMirroring, ImageOffset, ImagePolarity,
    ImageRotation, ImageScaling, InterpolationMode, MCode, Mirroring, Operation, Polarity,
    Rectangular, Rotation, Scaling, StepAndRepeat, Unit, ZeroOmission,
};
use std::collections::HashMap;
use std::convert::TryFrom;
use std::fmt::Debug;
use std::io::{BufReader, Cursor};
use std::panic::{AssertUnwindSafe, catch_unwind};

use super::IoError;

/// Options used when exporting a [`Sketch`] to Gerber.
#[derive(Clone, Copy, Debug)]
pub struct GerberExportOptions {
    /// Gerber file units. Defaults to millimeters.
    pub unit: Unit,
    /// Coordinate encoding used for emitted X/Y values.
    pub coordinate_format: CoordinateFormat,
}

impl Default for GerberExportOptions {
    fn default() -> Self {
        Self {
            unit: Unit::Millimeters,
            coordinate_format: CoordinateFormat::new(
                ZeroOmission::Leading,
                CoordinateMode::Absolute,
                4,
                6,
            ),
        }
    }
}

/// Parse Gerber data into a `Sketch`.
pub trait FromGerber<M>: Sized {
    fn from_gerber(gerber_data: &[u8], metadata: M) -> Result<Self, IoError>;
}

/// Serialize geometry to Gerber.
pub trait ToGerber {
    fn to_gerber(&self) -> Result<Vec<u8>, IoError>;
    fn to_gerber_with_options(&self, options: GerberExportOptions)
    -> Result<Vec<u8>, IoError>;
}

impl<M> FromGerber<M> for Sketch<M>
where
    M: Clone + Debug + Send + Sync,
{
    fn from_gerber(gerber_data: &[u8], metadata: M) -> Result<Self, IoError> {
        preflight_gerber_input(gerber_data)?;

        let reader = BufReader::new(Cursor::new(gerber_data));
        let parsed = catch_unwind(AssertUnwindSafe(|| gerber_parser::parse(reader)))
            .map_err(|_| IoError::GerberParsing("Gerber parser panicked".to_string()))?;
        let doc =
            parsed.map_err(|(_doc, error)| IoError::GerberParsing(format!("{error:?}")))?;

        let errors = doc.errors();
        if !errors.is_empty() {
            let message = errors
                .iter()
                .map(|error| error.to_string())
                .collect::<Vec<_>>()
                .join("; ");
            return Err(IoError::GerberParsing(message));
        }

        let mut state =
            ImportState::<M>::new(doc.units.unwrap_or(Unit::Millimeters), metadata);
        for command in doc.commands() {
            state.apply_command(command, &doc.apertures)?;
        }

        Ok(state.sketch)
    }
}

fn preflight_gerber_input(gerber_data: &[u8]) -> Result<(), IoError> {
    let text = std::str::from_utf8(gerber_data)
        .map_err(|error| IoError::GerberParsing(format!("Invalid UTF-8: {error}")))?;

    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        if !line.contains('*') {
            return Err(IoError::GerberParsing(format!(
                "Gerber command is missing terminator: {line:?}"
            )));
        }
    }

    Ok(())
}

impl<M> ToGerber for Sketch<M>
where
    M: Clone + Debug + Send + Sync,
{
    fn to_gerber(&self) -> Result<Vec<u8>, IoError> {
        self.to_gerber_with_options(GerberExportOptions::default())
    }

    fn to_gerber_with_options(
        &self,
        options: GerberExportOptions,
    ) -> Result<Vec<u8>, IoError> {
        let mut commands = vec![
            FunctionCode::GCode(GCode::Comment(CommentContent::String(
                "Generated by csgrs".to_string(),
            )))
            .into(),
            ExtendedCode::Unit(options.unit).into(),
            ExtendedCode::CoordinateFormat(options.coordinate_format).into(),
            ExtendedCode::LoadPolarity(Polarity::Dark).into(),
            ExtendedCode::ApertureDefinition(ApertureDefinition::new(
                10,
                Aperture::Circle(Circle::new(0.01)),
            ))
            .into(),
            FunctionCode::DCode(DCode::SelectAperture(10)).into(),
            FunctionCode::GCode(GCode::InterpolationMode(InterpolationMode::Linear)).into(),
        ];

        for geometry in self.geometry.iter() {
            emit_geometry(geometry, &mut commands, options)?;
        }

        commands.push(FunctionCode::MCode(MCode::EndOfFile).into());

        let mut bytes = Vec::new();
        commands.serialize(&mut bytes)?;
        Ok(bytes)
    }
}

struct ImportState<M> {
    sketch: Sketch<M>,
    metadata: M,
    unit_scale: Real,
    current: Coord<Real>,
    selected_aperture: Option<i32>,
    interpolation_mode: InterpolationMode,
    polarity: Polarity,
    aperture_transform: ApertureTransform,
    image_transform: ImageTransform,
    step_repeat: Option<StepRepeatState>,
    region: Option<RegionBuilder>,
}

impl<M> ImportState<M>
where
    M: Clone + Debug + Send + Sync,
{
    fn new(unit: Unit, metadata: M) -> Self {
        Self {
            sketch: Sketch::empty(metadata.clone()),
            metadata,
            unit_scale: unit_scale(unit),
            current: Coord { x: 0.0, y: 0.0 },
            selected_aperture: None,
            interpolation_mode: InterpolationMode::Linear,
            polarity: Polarity::Dark,
            aperture_transform: ApertureTransform::default(),
            image_transform: ImageTransform::default(),
            step_repeat: None,
            region: None,
        }
    }

    fn apply_command(
        &mut self,
        command: &Command,
        apertures: &HashMap<i32, Aperture>,
    ) -> Result<(), IoError> {
        match command {
            Command::ExtendedCode(ExtendedCode::Unit(unit)) => {
                self.unit_scale = unit_scale(*unit);
            },
            Command::FunctionCode(FunctionCode::GCode(GCode::InterpolationMode(mode))) => {
                self.interpolation_mode = *mode;
            },
            Command::ExtendedCode(ExtendedCode::LoadPolarity(polarity)) => {
                self.polarity = *polarity;
            },
            Command::ExtendedCode(ExtendedCode::LoadMirroring(mirroring)) => {
                self.aperture_transform.mirroring = *mirroring;
            },
            Command::ExtendedCode(ExtendedCode::LoadScaling(scaling)) => {
                self.aperture_transform.scaling = *scaling;
            },
            Command::ExtendedCode(ExtendedCode::LoadRotation(rotation)) => {
                self.aperture_transform.rotation = *rotation;
            },
            Command::ExtendedCode(ExtendedCode::StepAndRepeat(step_repeat)) => {
                self.apply_step_repeat(step_repeat);
            },
            Command::ExtendedCode(ExtendedCode::AxisSelect(axis_select)) => {
                self.image_transform.axis_select = *axis_select;
            },
            Command::ExtendedCode(ExtendedCode::MirrorImage(mirroring)) => {
                self.image_transform.mirroring = *mirroring;
            },
            Command::ExtendedCode(ExtendedCode::OffsetImage(offset)) => {
                self.image_transform.offset = *offset;
            },
            Command::ExtendedCode(ExtendedCode::ScaleImage(scaling)) => {
                self.image_transform.scaling = *scaling;
            },
            Command::ExtendedCode(ExtendedCode::RotateImage(rotation)) => {
                self.image_transform.rotation = *rotation;
            },
            Command::ExtendedCode(ExtendedCode::ImagePolarity(polarity)) => {
                self.polarity = match polarity {
                    ImagePolarity::Positive => Polarity::Dark,
                    ImagePolarity::Negative => Polarity::Clear,
                };
            },
            Command::FunctionCode(FunctionCode::GCode(GCode::RegionMode(enabled))) => {
                if *enabled {
                    self.region = Some(RegionBuilder::new());
                } else if let Some(region) = self.region.take() {
                    if let Some(sketch) = region.into_sketch(self.metadata.clone()) {
                        self.apply_polarity(sketch);
                    }
                }
            },
            Command::FunctionCode(FunctionCode::DCode(DCode::SelectAperture(code))) => {
                self.selected_aperture = Some(*code);
            },
            Command::FunctionCode(FunctionCode::DCode(DCode::Operation(operation))) => {
                self.apply_operation(operation, apertures)?;
            },
            _ => {},
        }

        Ok(())
    }

    fn apply_step_repeat(&mut self, step_repeat: &StepAndRepeat) {
        self.step_repeat = match *step_repeat {
            StepAndRepeat::Open {
                repeat_x,
                repeat_y,
                distance_x,
                distance_y,
            } => Some(StepRepeatState {
                repeat_x,
                repeat_y,
                distance_x: (distance_x as Real) * self.unit_scale,
                distance_y: (distance_y as Real) * self.unit_scale,
            }),
            StepAndRepeat::Close => None,
        };
    }

    fn apply_polarity(&mut self, sketch: Sketch<M>) {
        let sketches = repeat_sketches(sketch, self.step_repeat);
        for sketch in sketches {
            self.sketch = match self.polarity {
                Polarity::Dark => self.sketch.union(&sketch),
                Polarity::Clear => self.sketch.difference(&sketch),
            };
        }
    }

    fn apply_operation(
        &mut self,
        operation: &Operation,
        apertures: &HashMap<i32, Aperture>,
    ) -> Result<(), IoError> {
        match operation {
            Operation::Move(coords) => {
                if let Some(coords) = coords {
                    self.current = resolve_coordinates(
                        coords,
                        self.current,
                        self.unit_scale,
                        self.image_transform,
                    );
                }
                if let Some(region) = &mut self.region {
                    region.move_to(self.current);
                }
            },
            Operation::Interpolate(coords, offset) => {
                let target = coords
                    .as_ref()
                    .map(|coords| {
                        resolve_coordinates(
                            coords,
                            self.current,
                            self.unit_scale,
                            self.image_transform,
                        )
                    })
                    .unwrap_or(self.current);

                let points = match (self.interpolation_mode, offset) {
                    (InterpolationMode::Linear, _) | (_, None) => vec![target],
                    (
                        InterpolationMode::ClockwiseCircular
                        | InterpolationMode::CounterclockwiseCircular,
                        Some(offset),
                    ) => approximate_arc(
                        self.current,
                        target,
                        resolve_offset(offset, self.unit_scale, self.image_transform),
                        self.interpolation_mode,
                    ),
                };

                if let Some(region) = &mut self.region {
                    for point in &points {
                        region.line_to(self.current, *point);
                        self.current = *point;
                    }
                    return Ok(());
                }

                let Some(code) = self.selected_aperture else {
                    self.current = target;
                    return Ok(());
                };
                let Some(aperture) = apertures.get(&code) else {
                    self.current = target;
                    return Ok(());
                };

                let mut start = self.current;
                for point in points {
                    if let Some(sketch) = trace_to_sketch(
                        aperture,
                        start,
                        point,
                        self.metadata.clone(),
                        self.unit_scale,
                        self.aperture_transform,
                    ) {
                        self.apply_polarity(sketch);
                    }
                    start = point;
                }
                self.current = start;
            },
            Operation::Flash(coords) => {
                if let Some(coords) = coords {
                    self.current = resolve_coordinates(
                        coords,
                        self.current,
                        self.unit_scale,
                        self.image_transform,
                    );
                }

                let Some(code) = self.selected_aperture else {
                    return Ok(());
                };
                let Some(aperture) = apertures.get(&code) else {
                    return Ok(());
                };
                if let Some(sketch) = flash_to_sketch(
                    aperture,
                    self.current,
                    self.metadata.clone(),
                    self.unit_scale,
                    self.aperture_transform,
                ) {
                    self.apply_polarity(sketch);
                }
            },
        }

        Ok(())
    }
}

struct RegionBuilder {
    current_ring: Vec<Coord<Real>>,
    rings: Vec<LineString<Real>>,
}

#[derive(Clone, Copy, Debug)]
struct StepRepeatState {
    repeat_x: u32,
    repeat_y: u32,
    distance_x: Real,
    distance_y: Real,
}

#[derive(Clone, Copy, Debug)]
struct ApertureTransform {
    mirroring: Mirroring,
    scaling: Scaling,
    rotation: Rotation,
}

impl Default for ApertureTransform {
    fn default() -> Self {
        Self {
            mirroring: Mirroring::None,
            scaling: Scaling { scale: 1.0 },
            rotation: Rotation { rotation: 0.0 },
        }
    }
}

#[derive(Clone, Copy, Debug)]
struct ImageTransform {
    axis_select: AxisSelect,
    mirroring: ImageMirroring,
    offset: ImageOffset,
    scaling: ImageScaling,
    rotation: ImageRotation,
}

impl Default for ImageTransform {
    fn default() -> Self {
        Self {
            axis_select: AxisSelect::AXBY,
            mirroring: ImageMirroring::None,
            offset: ImageOffset::default(),
            scaling: ImageScaling::default(),
            rotation: ImageRotation::None,
        }
    }
}

impl RegionBuilder {
    fn new() -> Self {
        Self {
            current_ring: Vec::new(),
            rings: Vec::new(),
        }
    }

    fn move_to(&mut self, point: Coord<Real>) {
        self.finish_ring();
        self.current_ring.push(point);
    }

    fn line_to(&mut self, start: Coord<Real>, end: Coord<Real>) {
        if self.current_ring.is_empty() {
            self.current_ring.push(start);
        }
        self.current_ring.push(end);
    }

    fn finish_ring(&mut self) {
        if self.current_ring.len() < 3 {
            self.current_ring.clear();
            return;
        }

        if self.current_ring.first() != self.current_ring.last() {
            let first = self.current_ring[0];
            self.current_ring.push(first);
        }

        self.rings
            .push(LineString::new(std::mem::take(&mut self.current_ring)));
    }

    fn into_sketch<M>(mut self, metadata: M) -> Option<Sketch<M>>
    where
        M: Clone + Debug + Send + Sync,
    {
        self.finish_ring();

        let mut rings = self
            .rings
            .into_iter()
            .filter(|ring| ring.0.len() >= 4)
            .collect::<Vec<_>>();
        if rings.is_empty() {
            return None;
        }

        let exterior = rings.remove(0);
        let polygon = GeoPolygon::new(exterior, rings);
        Some(Sketch::from_geo(
            GeometryCollection(vec![Geometry::Polygon(polygon)]),
            metadata,
        ))
    }
}

fn emit_geometry(
    geometry: &Geometry<Real>,
    commands: &mut Vec<Command>,
    options: GerberExportOptions,
) -> Result<(), IoError> {
    match geometry {
        Geometry::Polygon(polygon) => emit_polygon(polygon, commands, options)?,
        Geometry::MultiPolygon(multi_polygon) => {
            for polygon in multi_polygon {
                emit_polygon(polygon, commands, options)?;
            }
        },
        Geometry::Rect(rect) => emit_polygon(&rect.to_polygon(), commands, options)?,
        Geometry::Triangle(triangle) => {
            emit_polygon(&triangle.to_polygon(), commands, options)?
        },
        Geometry::GeometryCollection(collection) => {
            for geometry in collection {
                emit_geometry(geometry, commands, options)?;
            }
        },
        _ => {},
    }

    Ok(())
}

fn emit_polygon(
    polygon: &GeoPolygon<Real>,
    commands: &mut Vec<Command>,
    options: GerberExportOptions,
) -> Result<(), IoError> {
    commands.push(FunctionCode::GCode(GCode::RegionMode(true)).into());
    emit_ring(polygon.exterior(), commands, options)?;
    for interior in polygon.interiors() {
        emit_ring(interior, commands, options)?;
    }
    commands.push(FunctionCode::GCode(GCode::RegionMode(false)).into());
    Ok(())
}

fn emit_ring(
    ring: &LineString<Real>,
    commands: &mut Vec<Command>,
    options: GerberExportOptions,
) -> Result<(), IoError> {
    let Some(first) = ring.0.first() else {
        return Ok(());
    };

    commands.push(
        FunctionCode::DCode(DCode::Operation(Operation::Move(Some(gerber_coordinates(
            *first, options,
        )?))))
        .into(),
    );

    for coord in ring.0.iter().skip(1) {
        commands.push(
            FunctionCode::DCode(DCode::Operation(Operation::Interpolate(
                Some(gerber_coordinates(*coord, options)?),
                None,
            )))
            .into(),
        );
    }

    Ok(())
}

fn gerber_coordinates(
    coord: Coord<Real>,
    options: GerberExportOptions,
) -> Result<Coordinates, IoError> {
    let x = export_coordinate_number(coord.x, options)?;
    let y = export_coordinate_number(coord.y, options)?;
    Ok(Coordinates::new(x, y, options.coordinate_format))
}

fn export_coordinate_number(
    value: Real,
    options: GerberExportOptions,
) -> Result<CoordinateNumber, IoError> {
    let value = match options.unit {
        Unit::Millimeters => value as f64,
        Unit::Inches => (value as f64) / 25.4,
    };
    Ok(CoordinateNumber::try_from(value)?.validate(&options.coordinate_format)?)
}

fn resolve_coordinates(
    coords: &Coordinates,
    current: Coord<Real>,
    unit_scale: Real,
    image_transform: ImageTransform,
) -> Coord<Real> {
    let coord = Coord {
        x: coords
            .x
            .map(|x| (f64::from(x) as Real) * unit_scale)
            .unwrap_or(current.x),
        y: coords
            .y
            .map(|y| (f64::from(y) as Real) * unit_scale)
            .unwrap_or(current.y),
    };
    image_transform.apply_point(coord, unit_scale)
}

fn resolve_offset(
    offset: &CoordinateOffset,
    unit_scale: Real,
    image_transform: ImageTransform,
) -> Coord<Real> {
    let coord = Coord {
        x: offset
            .x
            .map(|x| (f64::from(x) as Real) * unit_scale)
            .unwrap_or(0.0),
        y: offset
            .y
            .map(|y| (f64::from(y) as Real) * unit_scale)
            .unwrap_or(0.0),
    };
    image_transform.apply_vector(coord)
}

impl ImageTransform {
    fn apply_point(self, point: Coord<Real>, unit_scale: Real) -> Coord<Real> {
        let mut point = match self.axis_select {
            AxisSelect::AXBY => point,
            AxisSelect::AYBX => Coord {
                x: point.y,
                y: point.x,
            },
        };

        point.x *= self.scaling.a as Real;
        point.y *= self.scaling.b as Real;

        match self.mirroring {
            ImageMirroring::None => {},
            ImageMirroring::A => point.x = -point.x,
            ImageMirroring::B => point.y = -point.y,
            ImageMirroring::AB => {
                point.x = -point.x;
                point.y = -point.y;
            },
        }

        point = rotate_coord(point, image_rotation_degrees(self.rotation));
        point.x += (self.offset.a as Real) * unit_scale;
        point.y += (self.offset.b as Real) * unit_scale;
        point
    }

    fn apply_vector(self, vector: Coord<Real>) -> Coord<Real> {
        let mut vector = match self.axis_select {
            AxisSelect::AXBY => vector,
            AxisSelect::AYBX => Coord {
                x: vector.y,
                y: vector.x,
            },
        };

        vector.x *= self.scaling.a as Real;
        vector.y *= self.scaling.b as Real;

        match self.mirroring {
            ImageMirroring::None => {},
            ImageMirroring::A => vector.x = -vector.x,
            ImageMirroring::B => vector.y = -vector.y,
            ImageMirroring::AB => {
                vector.x = -vector.x;
                vector.y = -vector.y;
            },
        }

        rotate_coord(vector, image_rotation_degrees(self.rotation))
    }
}

fn flash_to_sketch<M>(
    aperture: &Aperture,
    center: Coord<Real>,
    metadata: M,
    unit_scale: Real,
    aperture_transform: ApertureTransform,
) -> Option<Sketch<M>>
where
    M: Clone + Debug + Send + Sync,
{
    let mut sketch = match aperture {
        Aperture::Circle(circle) => {
            let radius =
                aperture_transform.scale_length((circle.diameter as Real) * unit_scale) * 0.5;
            let mut sketch = Sketch::circle(radius, 64, metadata.clone());
            if let Some(hole_diameter) = circle.hole_diameter {
                sketch = sketch.difference(&Sketch::circle(
                    aperture_transform.scale_length((hole_diameter as Real) * unit_scale)
                        * 0.5,
                    64,
                    metadata,
                ));
            }
            sketch
        },
        Aperture::Rectangle(rect) => {
            aperture_rect_sketch(rect, metadata, unit_scale, aperture_transform, false)
        },
        Aperture::Obround(rect) => {
            aperture_rect_sketch(rect, metadata, unit_scale, aperture_transform, true)
        },
        Aperture::Polygon(polygon) => {
            let radius =
                aperture_transform.scale_length((polygon.diameter as Real) * unit_scale) * 0.5;
            let rotation = polygon.rotation.unwrap_or(0.0) as Real;
            let mut sketch =
                Sketch::regular_ngon(polygon.vertices as usize, radius, metadata.clone())
                    .rotate(0.0, 0.0, rotation);
            if let Some(hole_diameter) = polygon.hole_diameter {
                sketch = sketch.difference(&Sketch::circle(
                    aperture_transform.scale_length((hole_diameter as Real) * unit_scale)
                        * 0.5,
                    64,
                    metadata,
                ));
            }
            sketch
        },
        Aperture::Macro(..) => return None,
    };

    sketch = apply_aperture_transform(sketch, aperture_transform);
    Some(sketch.translate(center.x, center.y, 0.0))
}

impl ApertureTransform {
    fn scale_length(self, value: Real) -> Real {
        value * (self.scaling.scale as Real)
    }
}

fn aperture_rect_sketch<M>(
    rect: &Rectangular,
    metadata: M,
    unit_scale: Real,
    aperture_transform: ApertureTransform,
    rounded: bool,
) -> Sketch<M>
where
    M: Clone + Debug + Send + Sync,
{
    let width = aperture_transform.scale_length((rect.x as Real) * unit_scale);
    let height = aperture_transform.scale_length((rect.y as Real) * unit_scale);
    let mut sketch = if rounded {
        Sketch::rounded_rectangle(width, height, width.min(height) * 0.5, 16, metadata.clone())
    } else {
        Sketch::rectangle(width, height, metadata.clone())
    }
    .translate(-width * 0.5, -height * 0.5, 0.0);

    if let Some(hole_diameter) = rect.hole_diameter {
        sketch = sketch.difference(&Sketch::circle(
            aperture_transform.scale_length((hole_diameter as Real) * unit_scale) * 0.5,
            64,
            metadata,
        ));
    }

    sketch
}

fn trace_to_sketch<M>(
    aperture: &Aperture,
    start: Coord<Real>,
    end: Coord<Real>,
    metadata: M,
    unit_scale: Real,
    aperture_transform: ApertureTransform,
) -> Option<Sketch<M>>
where
    M: Clone + Debug + Send + Sync,
{
    if nearly_same(start, end) {
        return flash_to_sketch(aperture, start, metadata, unit_scale, aperture_transform);
    }

    match aperture {
        Aperture::Circle(circle) => {
            let radius =
                aperture_transform.scale_length((circle.diameter as Real) * unit_scale) * 0.5;
            Some(capsule_sketch(start, end, radius, metadata))
        },
        Aperture::Rectangle(_) | Aperture::Obround(_) | Aperture::Polygon(_) => {
            let points = aperture_outline_points(aperture, unit_scale, aperture_transform)?;
            let swept_points = points
                .iter()
                .flat_map(|point| {
                    [
                        Coord {
                            x: point.x + start.x,
                            y: point.y + start.y,
                        },
                        Coord {
                            x: point.x + end.x,
                            y: point.y + end.y,
                        },
                    ]
                })
                .collect::<Vec<_>>();
            polygon_from_coords(convex_hull(swept_points), metadata)
        },
        Aperture::Macro(..) => None,
    }
}

fn aperture_outline_points(
    aperture: &Aperture,
    unit_scale: Real,
    aperture_transform: ApertureTransform,
) -> Option<Vec<Coord<Real>>> {
    let points = match aperture {
        Aperture::Circle(circle) => {
            let radius =
                aperture_transform.scale_length((circle.diameter as Real) * unit_scale) * 0.5;
            circle_points(radius, 64)
        },
        Aperture::Rectangle(rect) => {
            let hw = aperture_transform.scale_length((rect.x as Real) * unit_scale) * 0.5;
            let hh = aperture_transform.scale_length((rect.y as Real) * unit_scale) * 0.5;
            vec![
                Coord { x: -hw, y: -hh },
                Coord { x: hw, y: -hh },
                Coord { x: hw, y: hh },
                Coord { x: -hw, y: hh },
            ]
        },
        Aperture::Obround(rect) => {
            let width = aperture_transform.scale_length((rect.x as Real) * unit_scale);
            let height = aperture_transform.scale_length((rect.y as Real) * unit_scale);
            rounded_rect_points(width, height, width.min(height) * 0.5, 16)
        },
        Aperture::Polygon(polygon) => {
            let radius =
                aperture_transform.scale_length((polygon.diameter as Real) * unit_scale) * 0.5;
            let rotation = polygon.rotation.unwrap_or(0.0) as Real;
            (0..polygon.vertices)
                .map(|i| {
                    let theta =
                        TAU * (i as Real) / (polygon.vertices as Real) + rotation.to_radians();
                    Coord {
                        x: radius * theta.cos(),
                        y: radius * theta.sin(),
                    }
                })
                .collect()
        },
        Aperture::Macro(..) => return None,
    };

    Some(
        points
            .into_iter()
            .map(|point| apply_aperture_transform_to_coord(point, aperture_transform))
            .collect(),
    )
}

fn capsule_sketch<M>(
    start: Coord<Real>,
    end: Coord<Real>,
    radius: Real,
    metadata: M,
) -> Sketch<M>
where
    M: Clone + Debug + Send + Sync,
{
    let dx = end.x - start.x;
    let dy = end.y - start.y;
    let length = (dx * dx + dy * dy).sqrt();
    if length <= tolerance() {
        return Sketch::circle(radius, 64, metadata).translate(start.x, start.y, 0.0);
    }

    let nx = -dy / length;
    let ny = dx / length;
    let start_angle = ny.atan2(nx);
    let end_angle = (-ny).atan2(-nx);
    let mut points = vec![
        Coord {
            x: start.x + radius * nx,
            y: start.y + radius * ny,
        },
        Coord {
            x: end.x + radius * nx,
            y: end.y + radius * ny,
        },
    ];
    points.extend(
        arc_points(end, radius, start_angle, end_angle, true, 24)
            .into_iter()
            .skip(1),
    );
    points.push(Coord {
        x: start.x - radius * nx,
        y: start.y - radius * ny,
    });
    points.extend(
        arc_points(start, radius, end_angle, start_angle, true, 24)
            .into_iter()
            .skip(1),
    );
    polygon_from_coords(points, metadata.clone()).unwrap_or_else(|| Sketch::empty(metadata))
}

fn approximate_arc(
    start: Coord<Real>,
    end: Coord<Real>,
    offset: Coord<Real>,
    mode: InterpolationMode,
) -> Vec<Coord<Real>> {
    let center = Coord {
        x: start.x + offset.x,
        y: start.y + offset.y,
    };
    let radius = ((start.x - center.x).powi(2) + (start.y - center.y).powi(2)).sqrt();
    if radius <= tolerance() {
        return vec![end];
    }

    let start_angle = (start.y - center.y).atan2(start.x - center.x);
    let mut end_angle = (end.y - center.y).atan2(end.x - center.x);
    let clockwise = mode == InterpolationMode::ClockwiseCircular;

    if nearly_same(start, end) {
        end_angle = if clockwise {
            start_angle - TAU
        } else {
            start_angle + TAU
        };
    }

    let points = arc_points(center, radius, start_angle, end_angle, clockwise, 32);
    points.into_iter().skip(1).collect()
}

fn arc_points(
    center: Coord<Real>,
    radius: Real,
    start_angle: Real,
    end_angle: Real,
    clockwise: bool,
    min_segments: usize,
) -> Vec<Coord<Real>> {
    let mut sweep = end_angle - start_angle;
    if clockwise && sweep >= 0.0 {
        sweep -= TAU;
    } else if !clockwise && sweep <= 0.0 {
        sweep += TAU;
    }

    let segments = ((sweep.abs() / (PI / 24.0)).ceil() as usize).max(min_segments);
    (0..=segments)
        .map(|i| {
            let angle = start_angle + sweep * (i as Real) / (segments as Real);
            Coord {
                x: center.x + radius * angle.cos(),
                y: center.y + radius * angle.sin(),
            }
        })
        .collect()
}

fn circle_points(radius: Real, segments: usize) -> Vec<Coord<Real>> {
    (0..segments)
        .map(|i| {
            let theta = TAU * (i as Real) / (segments as Real);
            Coord {
                x: radius * theta.cos(),
                y: radius * theta.sin(),
            }
        })
        .collect()
}

fn rounded_rect_points(
    width: Real,
    height: Real,
    radius: Real,
    corner_segments: usize,
) -> Vec<Coord<Real>> {
    let radius = radius.min(width * 0.5).min(height * 0.5);
    if radius <= tolerance() {
        let hw = width * 0.5;
        let hh = height * 0.5;
        return vec![
            Coord { x: -hw, y: -hh },
            Coord { x: hw, y: -hh },
            Coord { x: hw, y: hh },
            Coord { x: -hw, y: hh },
        ];
    }

    let centers = [
        (width * 0.5 - radius, height * 0.5 - radius, 0.0),
        (-width * 0.5 + radius, height * 0.5 - radius, PI * 0.5),
        (-width * 0.5 + radius, -height * 0.5 + radius, PI),
        (width * 0.5 - radius, -height * 0.5 + radius, PI * 1.5),
    ];
    centers
        .into_iter()
        .flat_map(|(cx, cy, start)| {
            (0..=corner_segments).map(move |i| {
                let theta = start + (PI * 0.5) * (i as Real) / (corner_segments as Real);
                Coord {
                    x: cx + radius * theta.cos(),
                    y: cy + radius * theta.sin(),
                }
            })
        })
        .collect()
}

fn polygon_from_coords<M>(mut points: Vec<Coord<Real>>, metadata: M) -> Option<Sketch<M>>
where
    M: Clone + Debug + Send + Sync,
{
    if points.len() < 3 {
        return None;
    }
    if points.first() != points.last() {
        points.push(points[0]);
    }
    Some(Sketch::from_geo(
        GeometryCollection(vec![Geometry::Polygon(GeoPolygon::new(
            LineString::new(points),
            Vec::new(),
        ))]),
        metadata,
    ))
}

fn repeat_sketches<M>(
    sketch: Sketch<M>,
    step_repeat: Option<StepRepeatState>,
) -> Vec<Sketch<M>>
where
    M: Clone + Debug + Send + Sync,
{
    let Some(step_repeat) = step_repeat else {
        return vec![sketch];
    };

    let mut sketches = Vec::new();
    for x in 0..step_repeat.repeat_x {
        for y in 0..step_repeat.repeat_y {
            sketches.push(sketch.translate(
                (x as Real) * step_repeat.distance_x,
                (y as Real) * step_repeat.distance_y,
                0.0,
            ));
        }
    }
    sketches
}

fn apply_aperture_transform<M>(
    sketch: Sketch<M>,
    aperture_transform: ApertureTransform,
) -> Sketch<M>
where
    M: Clone + Debug + Send + Sync,
{
    let (sx, sy) = match aperture_transform.mirroring {
        Mirroring::None => (1.0, 1.0),
        Mirroring::X => (-1.0, 1.0),
        Mirroring::Y => (1.0, -1.0),
        Mirroring::XY => (-1.0, -1.0),
    };
    sketch
        .scale(sx, sy, 1.0)
        .rotate(0.0, 0.0, aperture_transform.rotation.rotation as Real)
}

fn apply_aperture_transform_to_coord(
    point: Coord<Real>,
    aperture_transform: ApertureTransform,
) -> Coord<Real> {
    let mut point = point;
    match aperture_transform.mirroring {
        Mirroring::None => {},
        Mirroring::X => point.x = -point.x,
        Mirroring::Y => point.y = -point.y,
        Mirroring::XY => {
            point.x = -point.x;
            point.y = -point.y;
        },
    }
    rotate_coord(point, aperture_transform.rotation.rotation as Real)
}

fn rotate_coord(point: Coord<Real>, degrees: Real) -> Coord<Real> {
    let radians = degrees.to_radians();
    let (sin, cos) = radians.sin_cos();
    Coord {
        x: point.x * cos - point.y * sin,
        y: point.x * sin + point.y * cos,
    }
}

fn image_rotation_degrees(rotation: ImageRotation) -> Real {
    match rotation {
        ImageRotation::None => 0.0,
        ImageRotation::CCW_90 => 90.0,
        ImageRotation::CCW_180 => 180.0,
        ImageRotation::CCW_270 => 270.0,
    }
}

fn convex_hull(mut points: Vec<Coord<Real>>) -> Vec<Coord<Real>> {
    points.sort_by(|a, b| a.x.total_cmp(&b.x).then_with(|| a.y.total_cmp(&b.y)));
    points.dedup_by(|a, b| nearly_same(*a, *b));

    if points.len() <= 3 {
        return points;
    }

    let mut lower = Vec::new();
    for point in &points {
        while lower.len() >= 2
            && cross(lower[lower.len() - 2], lower[lower.len() - 1], *point) <= 0.0
        {
            lower.pop();
        }
        lower.push(*point);
    }

    let mut upper = Vec::new();
    for point in points.iter().rev() {
        while upper.len() >= 2
            && cross(upper[upper.len() - 2], upper[upper.len() - 1], *point) <= 0.0
        {
            upper.pop();
        }
        upper.push(*point);
    }

    lower.pop();
    upper.pop();
    lower.extend(upper);
    lower
}

fn cross(origin: Coord<Real>, a: Coord<Real>, b: Coord<Real>) -> Real {
    (a.x - origin.x) * (b.y - origin.y) - (a.y - origin.y) * (b.x - origin.x)
}

fn nearly_same(a: Coord<Real>, b: Coord<Real>) -> bool {
    (a.x - b.x).abs() <= tolerance() && (a.y - b.y).abs() <= tolerance()
}

fn unit_scale(unit: Unit) -> Real {
    match unit {
        Unit::Millimeters => 1.0,
        Unit::Inches => 25.4,
    }
}

#[cfg(test)]
mod tests {
    use super::{FromGerber, ToGerber};
    use crate::float_types::PI;
    use crate::sketch::Sketch;
    use geo::{Area, BoundingRect, Geometry};

    #[test]
    fn exports_and_imports_square_region() {
        let square = Sketch::<()>::square(5.0, ());

        let gerber = square.to_gerber().unwrap();
        let gerber_text = String::from_utf8(gerber.clone()).unwrap();
        assert!(gerber_text.contains("%FSLAX46Y46*%"));
        assert!(gerber_text.contains("G36*"));
        assert!(gerber_text.contains("G37*"));

        let parsed = Sketch::<()>::from_gerber(&gerber, ()).unwrap();
        let bounds = parsed.geometry.bounding_rect().unwrap();
        assert_eq!(bounds.min().x, 0.0);
        assert_eq!(bounds.min().y, 0.0);
        assert_eq!(bounds.max().x, 5.0);
        assert_eq!(bounds.max().y, 5.0);
    }

    #[test]
    fn imports_circle_flash() {
        let gerber = b"G04 flash*\n%MOMM*%\n%FSLAX46Y46*%\n%ADD10C,2*%\nD10*\nX3000000Y4000000D03*\nM02*\n";

        let parsed = Sketch::<()>::from_gerber(gerber, ()).unwrap();
        let bounds = parsed.geometry.bounding_rect().unwrap();
        assert!((bounds.min().x - 2.0).abs() < 1.0e-6);
        assert!((bounds.max().x - 4.0).abs() < 1.0e-6);
        assert!((bounds.min().y - 3.0).abs() < 1.0e-6);
        assert!((bounds.max().y - 5.0).abs() < 1.0e-6);
    }

    #[test]
    fn imports_circular_trace_as_capsule() {
        let gerber = b"G04 trace*\n%MOMM*%\n%FSLAX46Y46*%\n%ADD10C,1*%\nD10*\nX0Y0D02*\nX4000000Y0D01*\nM02*\n";

        let parsed = Sketch::<()>::from_gerber(gerber, ()).unwrap();
        let bounds = parsed.geometry.bounding_rect().unwrap();
        assert!((bounds.min().x + 0.5).abs() < 1.0e-6);
        assert!((bounds.max().x - 4.5).abs() < 1.0e-6);
        assert!((bounds.min().y + 0.5).abs() < 1.0e-6);
        assert!((bounds.max().y - 0.5).abs() < 1.0e-6);
    }

    #[test]
    fn imports_rectangular_trace_as_sweep() {
        let gerber = b"G04 trace*\n%MOMM*%\n%FSLAX46Y46*%\n%ADD10R,1X2*%\nD10*\nX0Y0D02*\nX4000000Y0D01*\nM02*\n";

        let parsed = Sketch::<()>::from_gerber(gerber, ()).unwrap();
        let bounds = parsed.geometry.bounding_rect().unwrap();
        assert!((bounds.min().x + 0.5).abs() < 1.0e-6);
        assert!((bounds.max().x - 4.5).abs() < 1.0e-6);
        assert!((bounds.min().y + 1.0).abs() < 1.0e-6);
        assert!((bounds.max().y - 1.0).abs() < 1.0e-6);
    }

    #[test]
    fn imports_arc_trace() {
        let gerber = b"G04 arc*\n%MOMM*%\n%FSLAX46Y46*%\n%ADD10C,0.2*%\nD10*\nX1000000Y0D02*\nG03X0Y1000000I-1000000J0D01*\nM02*\n";

        let parsed = Sketch::<()>::from_gerber(gerber, ()).unwrap();
        let bounds = parsed.geometry.bounding_rect().unwrap();
        assert!(bounds.min().x >= -0.11);
        assert!(bounds.min().y >= -0.11);
        assert!((bounds.max().x - 1.1).abs() < 0.02);
        assert!((bounds.max().y - 1.1).abs() < 0.02);
    }

    #[test]
    fn imports_step_repeat() {
        let gerber = b"G04 step repeat*\n%MOMM*%\n%FSLAX46Y46*%\n%ADD10C,1*%\nD10*\n%SRX2Y2I2J3*%\nX0Y0D03*\n%SR*%\nM02*\n";

        let parsed = Sketch::<()>::from_gerber(gerber, ()).unwrap();
        let bounds = parsed.geometry.bounding_rect().unwrap();
        assert!((bounds.min().x + 0.5).abs() < 1.0e-6);
        assert!((bounds.max().x - 2.5).abs() < 1.0e-6);
        assert!((bounds.min().y + 0.5).abs() < 1.0e-6);
        assert!((bounds.max().y - 3.5).abs() < 1.0e-6);
    }

    #[test]
    fn imports_load_rotation_for_flashes() {
        let gerber = b"G04 rotated flash*\n%MOMM*%\n%FSLAX46Y46*%\n%ADD10R,1X2*%\nD10*\n%LR90*%\nX0Y0D03*\nM02*\n";

        let parsed = Sketch::<()>::from_gerber(gerber, ()).unwrap();
        let bounds = parsed.geometry.bounding_rect().unwrap();
        assert!((bounds.min().x + 1.0).abs() < 1.0e-6);
        assert!((bounds.max().x - 1.0).abs() < 1.0e-6);
        assert!((bounds.min().y + 0.5).abs() < 1.0e-6);
        assert!((bounds.max().y - 0.5).abs() < 1.0e-6);
    }

    #[test]
    fn imports_aperture_holes() {
        let gerber = b"G04 aperture hole*\n%MOMM*%\n%FSLAX46Y46*%\n%ADD10C,4X2*%\nD10*\nX0Y0D03*\nM02*\n";

        let parsed = Sketch::<()>::from_gerber(gerber, ()).unwrap();
        let area = parsed.to_multipolygon().unsigned_area();
        assert!((area - (PI * 3.0)).abs() < 0.05);
    }

    #[test]
    fn imports_clear_polarity_as_difference() {
        let gerber = b"G04 clear polarity*\n%MOMM*%\n%FSLAX46Y46*%\n%LPD*%\nG36*\nX0Y0D02*\nX4000000Y0D01*\nX4000000Y4000000D01*\nX0Y4000000D01*\nX0Y0D01*\nG37*\n%ADD10R,2X2*%\nD10*\n%LPC*%\nX2000000Y2000000D03*\nM02*\n";

        let parsed = Sketch::<()>::from_gerber(gerber, ()).unwrap();
        let area = parsed.to_multipolygon().unsigned_area();
        assert!((area - 12.0).abs() < 1.0e-6);
    }

    #[test]
    fn ignores_non_area_geometry_on_export() {
        let sketch = Sketch::<()>::from_geo(
            geo::GeometryCollection(vec![Geometry::Point(geo::Point::new(1.0, 2.0))]),
            (),
        );

        let gerber = String::from_utf8(sketch.to_gerber().unwrap()).unwrap();
        assert!(gerber.ends_with("M02*\n"));
    }
}
