#![doc = " OBJ file format support"]
#![doc = ""]
#![doc = " This module provides import and export functionality for Wavefront OBJ files,"]
#![doc = " a widely-supported 3D file format used by many modeling and rendering applications."]

use crate::mesh::Mesh;
use crate::polygon::Polygon;
#[cfg(feature = "sketch")]
use crate::sketch::Profile;
use crate::triangulated::IndexedTriangulated3D;
use crate::vertex::Vertex;
use hyperlattice::{Point3, Real, Vector3};
use std::fmt::Debug;
use std::io::{BufRead, Write};

use super::{IoError, finite_f64, single_line_metadata};

type ObjFace = Vec<(usize, usize)>;
type ObjBuffers = (Vec<Point3>, Vec<Vector3>, Vec<ObjFace>);

fn checked_obj_index(index: usize, limit: &'static str) -> Result<usize, IoError> {
    index.checked_add(1).ok_or(IoError::SizeOverflow {
        format: "OBJ",
        limit,
    })
}

fn invalid_obj_data(message: impl Into<String>) -> IoError {
    IoError::MalformedInput(format!("OBJ: {}", message.into()))
}

fn invalid_obj_data_at_line(line: usize, message: impl Into<String>) -> IoError {
    invalid_obj_data(format!("line {line}: {}", message.into()))
}

fn obj_line_error(line: usize, error: IoError) -> IoError {
    invalid_obj_data_at_line(line, error.to_string())
}

fn build_obj_buffers<T: IndexedTriangulated3D>(shape: &T) -> Result<ObjBuffers, IoError> {
    let indexed = shape.indexed_triangles();
    for face in &indexed.faces {
        for &(position, normal) in face {
            if position >= indexed.positions.len() || normal >= indexed.normals.len() {
                return Err(IoError::Geometry {
                    format: "OBJ",
                    detail: "indexed triangle references missing vertex data".into(),
                });
            }
            checked_obj_index(position, "one-based vertex index")?;
            checked_obj_index(normal, "one-based normal index")?;
        }
    }
    let faces = indexed.faces.into_iter().map(Vec::from).collect();
    Ok((indexed.positions, indexed.normals, faces))
}

#[doc = " Export any `Triangulated3D` shape to OBJ format as a string"]
#[doc = ""]
#[doc = " Creates a Wavefront OBJ file containing all triangles from `shape`."]
#[doc = ""]
#[doc = " # Arguments"]
#[doc = " * `object_name` - Name for the object in the OBJ file"]
pub fn to_obj<T: IndexedTriangulated3D>(
    shape: &T,
    object_name: &str,
) -> Result<String, IoError> {
    let object_name = single_line_metadata(object_name, "OBJ", "object name")?;
    if object_name.contains('#') {
        return Err(IoError::InvalidMetadata {
            format: "OBJ",
            field: "object name",
        });
    }
    let (vertices, normals, faces) = build_obj_buffers(shape)?;

    let mut obj_content = String::new();
    obj_content.push_str("# Generated by csgrs library\n");
    obj_content.push_str(&format!("# Object: {object_name}\n"));
    obj_content.push_str("# https://github.com/timschmidt/csgrs\n\n");
    obj_content.push_str(&format!("o {object_name}\n\n"));

    for vertex in &vertices {
        obj_content.push_str(&format!(
            "v {:.17} {:.17} {:.17}\n",
            finite_f64(&vertex.x, "OBJ", "vertex x")?,
            finite_f64(&vertex.y, "OBJ", "vertex y")?,
            finite_f64(&vertex.z, "OBJ", "vertex z")?
        ));
    }
    obj_content.push('\n');

    for normal in &normals {
        obj_content.push_str(&format!(
            "vn {:.17} {:.17} {:.17}\n",
            finite_f64(&normal.0[0], "OBJ", "normal x")?,
            finite_f64(&normal.0[1], "OBJ", "normal y")?,
            finite_f64(&normal.0[2], "OBJ", "normal z")?
        ));
    }
    obj_content.push('\n');

    for face in &faces {
        #[allow(clippy::single_char_add_str)]
        obj_content.push_str("f");
        for (vertex_idx, normal_idx) in face {
            obj_content.push_str(&format!(
                " {}//{}",
                checked_obj_index(*vertex_idx, "one-based vertex index")?,
                checked_obj_index(*normal_idx, "one-based normal index")?
            ));
        }
        obj_content.push('\n');
    }

    Ok(obj_content)
}

#[doc = " Export any `Triangulated3D` shape to an OBJ file"]
#[doc = ""]
#[doc = " # Arguments"]
#[doc = " * `writer` - Where to write the OBJ data"]
#[doc = " * `object_name` - Name for the object in the OBJ file"]
pub fn write_obj<T: IndexedTriangulated3D, W: Write>(
    shape: &T,
    writer: &mut W,
    object_name: &str,
) -> Result<(), IoError> {
    let obj_content = to_obj(shape, object_name)?;
    writer.write_all(obj_content.as_bytes())?;
    Ok(())
}

impl<M: Clone + Debug + Send + Sync> Mesh<M> {
    #[doc = " Export this Mesh to OBJ format as a string"]
    pub fn to_obj(&self, object_name: &str) -> Result<String, IoError> {
        self::to_obj(self, object_name)
    }

    #[doc = " Export this Mesh to an OBJ file"]
    pub fn write_obj<W: Write>(
        &self,
        writer: &mut W,
        object_name: &str,
    ) -> Result<(), IoError> {
        self::write_obj(self, writer, object_name)
    }

    #[doc = " Import a Mesh from OBJ file data"]
    #[doc = ""]
    #[doc = " # Arguments"]
    #[doc = " * `reader` - Source of OBJ data"]
    #[doc = " * `metadata` - Optional metadata to attach to all polygons"]
    ///
    /// Primitive OBJ coordinates are accepted only after they promote through
    /// the shared hyperlattice boundary adapters. Vertex normals are
    /// checked-normalized before entering mesh state, so non-finite or zero
    /// normals fail as malformed OBJ data rather than being silently sanitized
    /// by [`Vertex::new`]. This keeps file import aligned with Yap, "Towards
    /// Exact Geometric Computation," *Computational Geometry* 7(1-2), 1997
    /// (<https://doi.org/10.1016/0925-7721(95)00040-2>), while retaining the
    /// Wavefront OBJ `v`/`vn` finite boundary format.
    pub fn from_obj<R: BufRead>(reader: R, metadata: M) -> Result<Mesh<M>, IoError> {
        let mut vertices = Vec::new();
        let mut normals = Vec::new();
        let mut polygons = Vec::new();

        for (line_index, line_result) in reader.lines().enumerate() {
            let line_number = line_index + 1;
            let line = line_result?;
            let line = line.split('#').next().unwrap_or("").trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.is_empty() {
                continue;
            }
            match parts[0] {
                "v" => {
                    if parts.len() < 4 {
                        return Err(invalid_obj_data_at_line(
                            line_number,
                            "vertex line needs three coordinates",
                        ));
                    }
                    let x: Real = parts[1].parse().map_err(|e| {
                        invalid_obj_data_at_line(
                            line_number,
                            format!("Invalid vertex x coordinate: {e}"),
                        )
                    })?;
                    let y: Real = parts[2].parse().map_err(|e| {
                        invalid_obj_data_at_line(
                            line_number,
                            format!("Invalid vertex y coordinate: {e}"),
                        )
                    })?;
                    let z: Real = parts[3].parse().map_err(|e| {
                        invalid_obj_data_at_line(
                            line_number,
                            format!("Invalid vertex z coordinate: {e}"),
                        )
                    })?;
                    if parts.len() > 5 {
                        return Err(IoError::Unsupported {
                            format: "OBJ",
                            detail: format!(
                                "line {line_number}: vertex color extensions are not supported"
                            ),
                        });
                    }
                    let point = if let Some(weight) = parts.get(4) {
                        let weight: Real = weight.parse().map_err(|error| {
                            IoError::MalformedInput(format!(
                                "OBJ line {line_number}: invalid homogeneous weight: {error}"
                            ))
                        })?;
                        Point3::new(
                            (x / &weight).map_err(|error| IoError::MalformedInput(format!(
                                "OBJ line {line_number}: invalid homogeneous weight: {error}"
                            )))?,
                            (y / &weight).map_err(|error| IoError::MalformedInput(format!(
                                "OBJ line {line_number}: invalid homogeneous weight: {error}"
                            )))?,
                            (z / &weight).map_err(|error| IoError::MalformedInput(format!(
                                "OBJ line {line_number}: invalid homogeneous weight: {error}"
                            )))?,
                        )
                    } else {
                        Point3::new(x, y, z)
                    };
                    vertices.push(point);
                },
                "vn" => {
                    if parts.len() != 4 {
                        return Err(invalid_obj_data_at_line(
                            line_number,
                            "normal line needs three coordinates",
                        ));
                    }
                    let x: Real = parts[1].parse().map_err(|e| {
                        invalid_obj_data_at_line(
                            line_number,
                            format!("Invalid normal x coordinate: {e}"),
                        )
                    })?;
                    let y: Real = parts[2].parse().map_err(|e| {
                        invalid_obj_data_at_line(
                            line_number,
                            format!("Invalid normal y coordinate: {e}"),
                        )
                    })?;
                    let z: Real = parts[3].parse().map_err(|e| {
                        invalid_obj_data_at_line(
                            line_number,
                            format!("Invalid normal z coordinate: {e}"),
                        )
                    })?;
                    let normal = Vector3::from_xyz(x, y, z).normalize_checked().map_err(|_| {
                        invalid_obj_data_at_line(
                            line_number,
                            "Invalid normal coordinate: OBJ normals must be finite and non-zero",
                        )
                    })?;
                    normals.push(normal);
                },
                "f" => {
                    if parts.len() < 4 {
                        return Err(invalid_obj_data_at_line(
                            line_number,
                            "face line needs at least three vertices",
                        ));
                    }
                    let face_vertices =
                        Self::parse_obj_face(&parts[1..], &vertices, &normals, line_number)?;
                    let has_normals = parts[1..]
                        .iter()
                        .map(|part| {
                            part.split('/').nth(2).is_some_and(|index| !index.is_empty())
                        })
                        .collect::<Vec<_>>();
                    if has_normals.iter().any(|present| *present)
                        && has_normals.iter().any(|present| !*present)
                    {
                        return Err(invalid_obj_data_at_line(
                            line_number,
                            "face mixes vertices with and without normals",
                        ));
                    }
                    let mut face = Polygon::new(face_vertices, metadata.clone());
                    if !has_normals.iter().any(|present| *present) {
                        face.set_new_normal();
                    }
                    let triangles = face.triangulate();
                    if triangles.is_empty() {
                        return Err(invalid_obj_data_at_line(
                            line_number,
                            "face could not be triangulated",
                        ));
                    }
                    for triangle in triangles {
                        polygons.push(Polygon::new(triangle.to_vec(), metadata.clone()));
                    }
                },
                "o" | "g" | "s" | "usemtl" | "mtllib" => {},
                "vt" => {
                    return Err(IoError::Unsupported {
                        format: "OBJ",
                        detail: format!(
                            "line {line_number}: texture coordinates are not supported"
                        ),
                    });
                },
                directive => {
                    return Err(IoError::Unsupported {
                        format: "OBJ",
                        detail: format!("line {line_number}: directive {directive:?}"),
                    });
                },
            }
        }

        if polygons.is_empty() {
            return Err(IoError::MalformedInput(
                "OBJ input contains no polygonal faces".into(),
            ));
        }
        Ok(Mesh::from_polygons(&polygons))
    }

    fn parse_obj_face(
        face_parts: &[&str],
        vertices: &[Point3],
        normals: &[Vector3],
        line_number: usize,
    ) -> Result<Vec<Vertex>, IoError> {
        let mut face_vertices = Vec::new();
        for part in face_parts {
            let indices: Vec<&str> = part.split('/').collect();
            if indices.len() > 3 {
                return Err(IoError::MalformedInput(format!(
                    "OBJ line {line_number}: face token has too many index fields"
                )));
            }
            if indices.get(1).is_some_and(|index| !index.is_empty()) {
                return Err(IoError::Unsupported {
                    format: "OBJ",
                    detail: format!(
                        "line {line_number}: texture-coordinate indices are not supported"
                    ),
                });
            }
            let vertex_idx = parse_obj_index(indices[0], "vertex", vertices.len())
                .map_err(|error| obj_line_error(line_number, error))?;
            let position = vertices[vertex_idx].clone();
            let normal = if indices.len() >= 3 && !indices[2].is_empty() {
                let normal_idx = parse_obj_index(indices[2], "normal", normals.len())
                    .map_err(|error| obj_line_error(line_number, error))?;
                normals[normal_idx].clone()
            } else {
                Vector3::z()
            };
            face_vertices.push(Vertex::new(position, normal));
        }
        Ok(face_vertices)
    }
}

fn parse_obj_index(raw: &str, label: &str, value_count: usize) -> Result<usize, IoError> {
    if raw.is_empty() {
        return Err(invalid_obj_data(format!(
            "face token is missing a {label} index"
        )));
    }

    let index = raw
        .parse::<isize>()
        .map_err(|error| invalid_obj_data(format!("Invalid {label} index: {error}")))?;

    let resolved = if index > 0 {
        usize::try_from(index).map_err(|_| invalid_obj_data("face index exceeds usize"))? - 1
    } else if index < 0 {
        value_count.checked_sub(index.unsigned_abs()).ok_or_else(|| {
            invalid_obj_data(format!("negative {label} index is out of range"))
        })?
    } else {
        return Err(invalid_obj_data(format!(
            "Invalid {label} index: OBJ indices are one-based"
        )));
    };

    if resolved >= value_count {
        return Err(invalid_obj_data(format!("{label} index is out of range")));
    }

    Ok(resolved)
}

#[cfg(feature = "sketch")]
impl Profile {
    #[doc = " Export this Profile to OBJ format as a string"]
    pub fn to_obj(&self, object_name: &str) -> Result<String, IoError> {
        self::to_obj(self, object_name)
    }

    #[doc = " Export this Profile to an OBJ file"]
    pub fn write_obj<W: Write>(
        &self,
        writer: &mut W,
        object_name: &str,
    ) -> Result<(), IoError> {
        self::write_obj(self, writer, object_name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::io::test_support::InvalidIndexed;
    use std::io::Cursor;

    #[test]
    fn from_obj_accepts_relative_negative_face_indices() {
        let obj = "\
v 0 0 0
v 1 0 0
v 0 1 0
f -3 -2 -1
";

        let mesh = Mesh::<()>::from_obj(Cursor::new(obj), ()).unwrap();

        assert_eq!(mesh.polygons.len(), 1);
        assert_eq!(mesh.polygons[0].vertices.len(), 3);
    }

    #[test]
    fn from_obj_reports_malformed_vertex_line() {
        let error = Mesh::<()>::from_obj(Cursor::new("v 0 0\n"), ()).unwrap_err();

        assert!(error.to_string().contains("line 1"));
        assert!(
            error
                .to_string()
                .contains("vertex line needs three coordinates")
        );
    }

    #[test]
    fn from_obj_reports_malformed_face_line() {
        let obj = "\
v 0 0 0
v 1 0 0
f 1 2
";
        let error = Mesh::<()>::from_obj(Cursor::new(obj), ()).unwrap_err();

        assert!(error.to_string().contains("line 3"));
        assert!(
            error
                .to_string()
                .contains("face line needs at least three vertices")
        );
    }

    #[test]
    fn from_obj_applies_homogeneous_weights() {
        let obj = "v 2 0 0 2\nv 0 2 0 2\nv 0 0 2 2\nf 1 2 3\n";
        let mesh = Mesh::<()>::from_obj(Cursor::new(obj), ()).unwrap();
        assert_eq!(mesh.polygons[0].vertices[0].position.x, Real::one());
    }

    #[test]
    fn from_obj_rejects_texture_data_deliberately() {
        let obj = "v 0 0 0\nv 1 0 0\nv 0 1 0\nvt 0 0\nf 1/1 2/1 3/1\n";
        let error = Mesh::<()>::from_obj(Cursor::new(obj), ()).unwrap_err();
        assert!(matches!(error, IoError::Unsupported { format: "OBJ", .. }));
    }

    #[test]
    fn object_name_cannot_inject_records() {
        let mesh = Mesh::<()>::cube(Real::one(), ());
        assert!(mesh.to_obj("safe\nf 1 2 3").is_err());
        assert!(mesh.to_obj("name#silently truncated").is_err());
    }

    #[test]
    fn to_obj_emits_round_trip_f64_precision() {
        let obj = "\
v 0 0 0
v 1 0 0
v 0 1 0
f 1 2 3
";
        let mesh = Mesh::<()>::from_obj(Cursor::new(obj), ()).unwrap();

        let exported = mesh.to_obj("triangle").unwrap();

        assert!(
            exported.contains("v 1.00000000000000000 0.00000000000000000 0.00000000000000000")
        );
        assert!(exported.contains("o triangle"));
        let reparsed = Mesh::<()>::from_obj(Cursor::new(exported), ()).unwrap();
        assert_eq!(reparsed.polygons.len(), 1);
    }

    #[test]
    fn from_obj_triangulates_concave_faces_without_a_triangle_fan() {
        let obj = "\
v 0 0 0
v 2 0 0
v 2 2 0
v 1 1 0
v 0 2 0
f 1 2 3 4 5
";

        let mesh = Mesh::<()>::from_obj(Cursor::new(obj), ()).unwrap();

        assert_eq!(mesh.polygons.len(), 3);
        assert!(
            mesh.polygons
                .iter()
                .all(|polygon| polygon.vertices.len() == 3)
        );
    }

    #[test]
    fn export_rejects_invalid_indices_and_index_overflow() {
        assert!(matches!(
            to_obj(&InvalidIndexed, "invalid"),
            Err(IoError::Geometry { format: "OBJ", .. })
        ));
        assert!(matches!(
            checked_obj_index(usize::MAX, "test index"),
            Err(IoError::SizeOverflow { format: "OBJ", .. })
        ));
    }
}
