//! Stanford PLY export for native Hypermesh triangles.

use super::{IoError, finite_f64, single_line_metadata};
use hyperlattice::Point3;
use hypermesh::{Triangle, TriangleMesh};
use std::cell::RefCell;
use std::io::Write;
use std::sync::Arc;

#[derive(Clone)]
struct CachedPly {
    positions: Arc<[Point3]>,
    triangles: Arc<[Triangle]>,
    comment: String,
    output: String,
}

thread_local! {
    static PLY_CACHE: RefCell<Vec<CachedPly>> = const { RefCell::new(Vec::new()) };
}

/// Export native triangle geometry as ASCII PLY with generated vertex normals.
pub fn to_ply(mesh: &TriangleMesh, comment: &str) -> Result<String, IoError> {
    let comment = single_line_metadata(comment, "PLY", "comment")?;
    if let Some(output) = PLY_CACHE.with_borrow(|entries| {
        entries
            .iter()
            .find(|entry| {
                Arc::ptr_eq(&entry.positions, &mesh.positions)
                    && Arc::ptr_eq(&entry.triangles, &mesh.triangles)
                    && entry.comment == comment
            })
            .map(|entry| entry.output.clone())
    }) {
        return Ok(output);
    }
    let buffers = mesh
        .exact_gpu_mesh_buffers()
        .map_err(|error| IoError::Geometry {
            format: "PLY",
            detail: error.to_string(),
        })?;
    let mut output = format!(
        "ply\nformat ascii 1.0\ncomment {comment}\ncomment Generated by csgrs\n\
         element vertex {}\nproperty double x\nproperty double y\nproperty double z\n\
         property double nx\nproperty double ny\nproperty double nz\n\
         element face {}\nproperty list uchar int vertex_indices\nend_header\n",
        buffers.vertices.len(),
        buffers.indices.len() / 3,
    );
    for (position, normal) in &buffers.vertices {
        output.push_str(&format!(
            "{:.17} {:.17} {:.17} {:.17} {:.17} {:.17}\n",
            finite_f64(&position[0], "PLY", "vertex x")?,
            finite_f64(&position[1], "PLY", "vertex y")?,
            finite_f64(&position[2], "PLY", "vertex z")?,
            finite_f64(&normal[0], "PLY", "normal x")?,
            finite_f64(&normal[1], "PLY", "normal y")?,
            finite_f64(&normal[2], "PLY", "normal z")?,
        ));
    }
    for face in buffers.indices.chunks_exact(3) {
        output.push_str(&format!("3 {} {} {}\n", face[0], face[1], face[2]));
    }
    PLY_CACHE.with_borrow_mut(|entries| {
        const CAPACITY: usize = 4;
        if entries.len() == CAPACITY {
            entries.remove(0);
        }
        entries.push(CachedPly {
            positions: Arc::clone(&mesh.positions),
            triangles: Arc::clone(&mesh.triangles),
            comment: comment.to_owned(),
            output: output.clone(),
        });
    });
    Ok(output)
}

/// Write ASCII PLY to a stream.
pub fn write_ply<W: Write>(
    mesh: &TriangleMesh,
    writer: &mut W,
    comment: &str,
) -> Result<(), IoError> {
    writer.write_all(to_ply(mesh, comment)?.as_bytes())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use hyperlattice::Real;
    use ply_rs::{parser::Parser, ply::DefaultElement};
    use std::io::Cursor;

    #[test]
    fn cube_output_parses() {
        let mesh = crate::solid::cube(Real::one());
        let output = to_ply(&mesh, "cube").unwrap();
        let parsed = Parser::<DefaultElement>::new()
            .read_ply(&mut Cursor::new(output.as_bytes()))
            .unwrap();
        assert_eq!(parsed.payload["face"].len(), 12);
    }
}
