//! Fuzz target for export object and file names.

#![no_main]

use csgrs::mesh::Mesh;
use hyperlattice::Real;
use libfuzzer_sys::fuzz_target;

fuzz_target!(|bytes: &[u8]| {
    let name = String::from_utf8_lossy(bytes);
    let mesh: Mesh<()> = Mesh::cube(Real::one(), ());

    if let Ok(obj) = mesh.to_obj(&name) {
        assert!(obj.contains("# Generated by csgrs library"));
        let mut written = Vec::new();
        csgrs::io::obj::write_obj(&mesh, &mut written, &name)
            .expect("validated OBJ name remains writable");
        assert_eq!(written, obj.as_bytes());
    }

    if let Ok(ascii) = mesh.to_stl_ascii(&name) {
        assert!(ascii.contains("facet normal"));
    }
    if let Ok(binary) = mesh.to_stl_binary(&name) {
        assert!(binary.len() >= 84);
    }

    if let Ok(ply) = mesh.to_ply(&name) {
        assert!(ply.starts_with("ply\n"));
        let mut written = Vec::new();
        csgrs::io::ply::write_ply(&mesh, &mut written, &name)
            .expect("validated PLY comment remains writable");
        assert_eq!(written, ply.as_bytes());
    }

    if let Ok(amf) = mesh.to_amf(&name, &name) {
        assert!(amf.contains("<amf"));
        let mut written = Vec::new();
        csgrs::io::amf::write_amf(&mesh, &mut written, &name, &name)
            .expect("validated AMF metadata remains writable");
        assert_eq!(written, amf.as_bytes());
        let colored = csgrs::io::amf::to_amf_with_color(
            &mesh,
            &name,
            &name,
            (Real::one(), Real::zero(), Real::zero()),
        )
        .expect("valid AMF metadata accepts a valid color");
        assert!(colored.contains("<material id=\"1\">"));
    }

    let gltf = mesh
        .to_gltf(&name)
        .expect("JSON can represent every UTF-8 object name");
    assert!(gltf.contains("\"asset\""));
    let mut written = Vec::new();
    csgrs::io::gltf::write_gltf(&mesh, &mut written, &name)
        .expect("every JSON name remains writable");
    assert_eq!(written, gltf.as_bytes());
});
