#![no_main]

use csgrs::mesh::Mesh;
use libfuzzer_sys::fuzz_target;

fuzz_target!(|bytes: &[u8]| {
    let name = String::from_utf8_lossy(bytes);
    let mesh: Mesh<()> = Mesh::cube(1.0, None);

    let obj = mesh.to_obj(&name);
    assert!(obj.contains("# Generated by csgrs library"));

    let ascii = mesh.to_stl_ascii(&name);
    assert!(ascii.contains("facet normal"));
    let binary = mesh.to_stl_binary(&name).expect("binary STL export");
    assert!(binary.len() >= 84);

    let ply = mesh.to_ply(&name);
    assert!(ply.starts_with("ply\n"));

    let amf = mesh.to_amf(&name, &name);
    assert!(amf.contains("<amf"));

    let gltf = mesh.to_gltf(&name);
    assert!(gltf.contains("\"asset\""));
});
